[uwsgi]
# Python application's entry point
module = secformuwsgi:application
plugin = apparmor
apparmor-profile = mt-uwsgi

# Don't use space with env setting.
env="SF_RF_WORKING_DIR=/var/www/uwsgi/secform.revolutionaryfront.org"
# Master process
master = true

# Number of worker processes
processes = 5

# Socket configuration (using UNIX socket)
#socket = /tmp/mass-texter.sock
#chmod-socket = 660
http-socket = 127.0.0.1:8194

# Cleanup on exit
vacuum = true

# PID file for managing the process
pidfile = /run/secform.revolutionaryfront.org.pid

# Log file location
logto = /var/log/uwsgi/secform.revolutionaryfront.org.log
http-auto-gzip = true
http-keepalive = 1
